// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.0 (Build Build 614 04/24/2018)
// Created on Wed Oct 05 09:43:24 2022

LR2 LR2_inst
(
	.A(A_sig) ,	// input [0:0] A_sig
	.B(B_sig) ,	// input [0:0] B_sig
	.P0(P0_sig) ,	// input  P0_sig
	.A(A_sig) ,	// input [1:1] A_sig
	.B(B_sig) ,	// input [1:1] B_sig
	.A(A_sig) ,	// input [2:2] A_sig
	.B(B_sig) ,	// input [2:2] B_sig
	.A(A_sig) ,	// input [3:3] A_sig
	.B(B_sig) ,	// input [3:3] B_sig
	.S(S_sig) ,	// output [0:0] S_sig
	.S(S_sig) ,	// output [1:1] S_sig
	.S(S_sig) ,	// output [2:2] S_sig
	.P(P_sig) ,	// output  P_sig
	.S(S_sig) 	// output [3:3] S_sig
);

